### ISSUE TITLE
Differences between set and feedback signal

### ISSUE THREAD

**Issue by s265452** [Kinovarobotics/kinova-ros#382]
Hi everyone,
I'm using kinova Jaco 2 7Dof, ROS Melodic.
IK solver: Trac-IK

If I set an orientation contraint to the end effector and I don't specify `enforce_joint_model_state_space:true` in ompl_planning.yaml, I lose the control of the manipulator as you can see in the video:

https://user-images.githubusercontent.com/88098137/155175527-527549da-08dd-472d-a091-5ef4e5797104.mp4

Can you explain the reason why the manipulator has this behaviour?

In the following picture I plot the Set & Feedback coming from topics:
```
/j2s7s300_driver/out/joint_state
/j2s7s300_driver/trajectory_controller/command
```
Thin Lines --> Feedback
Thick Lines --> Set

![untitled](https://user-images.githubusercontent.com/88098137/155295943-9b853ae5-5da1-4622-be0e-a44159876b5e.jpg)

**Comment by felixmaisonneuve** [comment]
Hi @s265452,

Here is the definition of the `enforce_joint_model_state_space` parameter from the MoveIt [documentation](https://ros-planning.github.io/moveit_tutorials/doc/ompl_interface/ompl_interface_tutorial.html#enforce-planning-in-joint-space)
>Depending on the planning problem MoveIt chooses between joint space and cartesian space for problem representation. Setting the group parameter enforce_joint_model_state_space enforces the use of joint space for all plans.
By default planning requests with orientation path constraints are sampled in cartesian space so that invoking IK serves as a generative sampler.
By enforcing joint space the planning process will use rejection sampling to find valid requests. Please not that this might increase planning time considerably.

I suppose there is a bug in the Trac-IK solver and it doesn't handle correctly your joint constraint to the end effector when solving in cartesian space. My guess is your gripper reaches an angle outside of your constraint, so the tracking finds another trajectory and your arm "flips around" and get stuck.
Forcing to use the joint space with `enforce_joint_model_state_space:true` when solving the IK prevent this.

You could try to monitor only your 7th joint (the one with the constraint) and check if it gets close/outside of your limits.

I feel like this is a bug with Trac-IK. I don't know what I can do to help you. Have you tried using a different IK solver and see if this also happens? You could try to remove/change to constraint as well.

Regards,
Felix

**Comment by s265452** [comment]
Mmm.. Thank you @felixmaisonneuve .
The problem still persist with other IK solver.

I have another question. What kind of signal are sent to the manipualtor in order to execute the trajectory? Position? Velocity? Effort?

**Comment by felixmaisonneuve** [comment]
I am not sure I understand your question. What do you call the "manipulator"?

MoveIt will publish [trajectory_msgs/JointTrajectory](http://docs.ros.org/en/melodic/api/trajectory_msgs/html/msg/JointTrajectory.html) messages on the `trajectory_controller/command` topic. `JointTrajectory` contains a list of [JointTrajectoryPoint](http://docs.ros.org/en/melodic/api/trajectory_msgs/html/msg/JointTrajectoryPoint.html) that each contains `positions`, `velocities`, `accelerations`, and `efforts`.

Our ros driver will then read the message on the topic and send commands based on the velocity values. You can see the JointTrajectoryController will subscribe to the `trajectory_controller/command` topic and call `CommandCB` when it reads a message.
https://github.com/Kinovarobotics/kinova-ros/blob/93f66822ec073827eac5de59ebc2a3c5f06bf17f/kinova_driver/src/kinova_joint_trajectory_controller.cpp#L24

`CommandCB` will then send velocity commands to the arm based on the velocity values received from MoveIt : 
https://github.com/Kinovarobotics/kinova-ros/blob/93f66822ec073827eac5de59ebc2a3c5f06bf17f/kinova_driver/src/kinova_joint_trajectory_controller.cpp#L157-L173

Does this answer your question?

Best,
Felix

**Comment by s265452** [comment]
So, CommandCB send VelocitySet signal in order to execute the trajectory. 
The ROS controller PID makes VelocitySet - VelocityFeedback . Is it correct?

Are Joints servomotors? 


I have some difficulties to understand what is the element that ensures the correct execution of the trajectory.
Is it che controller of the arm? 
Are they the controller of servomotors? 
Is it the ros_control node? In this case it seems that the controller is only proportional one. How can I read in the j2s7s300_control.yaml
  ```
    j2s7s300_joint_1:
        d: 0
        i: 0
        i_clamp: 10
        p: 2000
      j2s7s300_joint_2:
        d: 0
        i: 0
        i_clamp: 10
        p: 3000
      j2s7s300_joint_3:
        d: 0
        i: 0
        i_clamp: 10
        p: 1000
      j2s7s300_joint_4:
        d: 0
        i: 0
        i_clamp: 10
        p: 2000
      j2s7s300_joint_5:
        d: 0
        i: 0
        i_clamp: 10
        p: 200
      j2s7s300_joint_6:
        d: 0
        i: 0
        i_clamp: 10
        p: 500
      j2s7s300_joint_7:
        d: 0
        i: 0
        i_clamp: 10
        p: 200
```

What does it mean "i_clamp" ?
