### ISSUE TITLE
Segmentation fault in Torque Control

### ISSUE THREAD

**Issue by yepw** [Kinovarobotics/kinova-ros#393]
## Description
j2s7s300_driver crashes in torque control. It happens only with **Ethernet** connection. 
I tried to use gdb to backtrace the error:
```
[ INFO] [1654995649.967037899]: Switching to torque control
[ WARN] [1654995657.833677076]: destruction entered!
[Thread 0x7fffd67fc700 (LWP 8060) exited]
[Thread 0x7fffd6ffd700 (LWP 8059) exited]
[Thread 0x7fffd77fe700 (LWP 8058) exited]
[Thread 0x7fffd7fff700 (LWP 8057) exited]
[Thread 0x7fffeca1b700 (LWP 8055) exited]
[Thread 0x7fffeda1d700 (LWP 8053) exited]

Thread 1 "kinova_arm_driv" received signal SIGSEGV, Segmentation fault.
_dl_close (_map=0x0) at dl-close.c:819
819	dl-close.c: No such file or directory.
(gdb) backtrace
#0  _dl_close (_map=0x0) at dl-close.c:819
#1  0x00007ffff63e416f in __GI__dl_catch_exception (exception=exception@entry=0x7fffffffa580, 
    operate=0x7ffff3f2a070 <dlclose_doit>, args=0x0) at dl-error-skeleton.c:196
#2  0x00007ffff63e41ff in __GI__dl_catch_error (objname=0x5555557903b0, errstring=0x5555557903b8, 
    mallocedp=0x5555557903a8, operate=<optimized out>, args=<optimized out>) at dl-error-skeleton.c:215
#3  0x00007ffff3f2a745 in _dlerror_run (operate=operate@entry=0x7ffff3f2a070 <dlclose_doit>, args=0x0) at dlerror.c:162
#4  0x00007ffff3f2a0b3 in __dlclose (handle=<optimized out>) at dlclose.c:46
#5  0x00007fffedc464b4 in Ethernet_CloseAPI () at ../Kinova.API.EthCommandLayerUbuntu.cpp:698
#6  0x00007ffff6ea4fdd in kinova::KinovaComm::~KinovaComm() () from /home/uwgraphics/jaco_ws/devel/lib/libkinova_driver.so
#7  0x000055555556375d in main ()
(gdb) 

```

## Version

ROS distribution : melodic
Branch and commit you are using : melodic-devel

## Steps to reproduce

1. Connect to a jaco2 7DoF arm with Ethernet
2. `roslaunch kinova_bringup kinova_robot.launch kinova_robotType:=j2s7s300`
3. `rosservice call /j2s7s300_driver/in/set_torque_control_mode "state: 1"`
4. `rostopic pub -r 100 /j2s7s300_driver/in/joint_torque kinova_msgs/JointTorque "{joint1: 0.0, joint2: 0.0, joint3: 0.0, joint4: 0.0, joint5: 0.0, joint6: 0.0, joint7: 0.0}`
5. j2s7s300_driver node crashed. `[j2s7s300_driver-2] process has died [pid 6291, exit code -11, cmd /home/uwgraphics/jaco_ws/devel/lib/kinova_driver/kinova_arm_driver j2s7s300 __name:=j2s7s300_driver __log:=/home/uwgraphics/.ros/log/2b49b4ba-e9e9-11ec-b323-e4a471f97180/j2s7s300_driver-2.log].`

## Expected behavior

I wanted the robot to enter "zero gravity" mode and to move the robot by manually dragging it.

## Any other information

The same error occurred when running `rosrun kinova_demo gravity_compensated_mode.py j2s7s300`. However, when running `gravity_compensated_mode.py`, the robot did successfully enter the gravity compensated mode before the driver crashed.

My robot_parameters.yaml
```yaml
# Set this parameter to use a specific arm on your system    --> 
# serial_number: PJ00000001030703130

# Joint speed limit for joints 1, 2, 3
jointSpeedLimitParameter1: 10

# Joint speed limit for joints 4, 5, 6
jointSpeedLimitParameter2: 20

# payload: [COM COMx COMy COMz]
payload: [1.0, 0, 0, 0.05]

connection_type: Ethernet #USB

# Ethernet connection parameters
ethernet: {
  local_machine_IP: 192.168.100.100,
  subnet_mask: 255.255.255.0,
  local_cmd_port: 25015,
  local_broadcast_port: 25025
}

#Torque control parameters
#Do not change these parameters unless you want to change torque control behavior
torque_parameters: {
      publish_torque_with_gravity_compensation: true,
      use_estimated_COM_parameters: false,
    # if torque min/max sepecified, all min/max values need to be specified
    #  torque_min: [80, 80, 80, 80, 80, 80, 80],
    #  torque_max: [90, 90, 90, 90, 90, 90, 90],
    # Decides velocity threshold at which robot switches torque to position control (between 0 and 1)
    safety_factor: 1,
    # COM parameters
    # order [m1,m2,...,m7,x1,x2,...,x7,y1,y2,...y7,z1,z2,...z7]
    # com_parameters: [0,0,0,0,0,0,0, 0,0,0,0,0,0,0, 0,0,0,0,0,0,0, 0,0,0,0,0,0,0]
}

```
